### ISSUE TITLE
`onehot_goals.pth` file not found

### ISSUE THREAD

**Issue by yixiaoshenghua** [notmahi/miniBET#2]
## 🐛 Bug description

Error executing job with overrides: []
Error in call to target 'kitchen_env.get_goal_fn':
FileNotFoundError(2, 'No such file or directory')
full_key: goal_fn

Hello, 

When I run `python train.py`, I encounter a file not found issue. The specific reason seems to be that the `onehot_goals.pth` file is missing when the `goal_fn` function is called in `eval_on_env`, which in turn calls the `RelayKitchenTrajectoryDataset` function in `dataset.py`. This file is not included in the downloaded expert dataset "kitchen" after extracting it. Could you please upload the missing `onehot_goals.pth` file? Thank you!

**Comment by notmahi** [comment]
Hi,

You can download the file from the [original paper's](https://github.com/jeffacce/play-to-policy?tab=readme-ov-file) data release in this link: https://osf.io/q3dx2/
